import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

#Generated by ChatGPT 5.5
def moving_reduce(x, window_size, reducer=np.sum, mode="valid", pad_value=0):
    x = np.asarray(x)

    if window_size < 1:
        raise ValueError("window_size must be >= 1")

    if mode == "valid":
        padded = x

    elif mode == "same":
        left = (window_size - 1) // 2
        right = window_size - 1 - left
        padded = np.pad(x, (left, right), constant_values=pad_value)

    else:
        raise ValueError("mode must be 'valid' or 'same'")

    windows = sliding_window_view(padded, window_size)
    return reducer(windows, axis=-1)